# Generated by Django 5.1.6 on 2025-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
