# Generated by Django 5.1.6 on 2025-03-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_produkt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brand'),
        ),
    ]
